# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for more details
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - pkg/proto
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - gocyclo
    - revive
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
  gosec:
    excludes:
      - G104 # 忽略未检查的错误(某些场景)
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: .*_test\.go$
      linters:
        - errcheck
        - gosec
