// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/proto/daemon/daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DaemonVersion string                 `protobuf:"bytes,6,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MetricsRequest 指标上报请求
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON格式的指标数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MetricsResponse 指标上报响应
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ConfigRequest 配置请求
type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigType    string                 `protobuf:"bytes,2,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"` // 配置类型: "daemon" 或 "agent"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

// ConfigResponse 配置响应
type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	ConfigData    []byte                 `protobuf:"bytes,3,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"` // JSON或YAML格式的配置数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigResponse) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

// UpdateRequest 更新请求
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`                        // 组件类型: "daemon" 或 "agent"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // 目标版本号
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // 更新包下载URL
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`                                  // 文件哈希(SHA256)
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                        // 数字签名(用于验证)
	UpdateData    []byte                 `protobuf:"bytes,7,opt,name=update_data,json=updateData,proto3" json:"update_data,omitempty"`    // 更新包数据(可选,用于小文件直接传输)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *UpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UpdateRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UpdateRequest) GetUpdateData() []byte {
	if x != nil {
		return x.UpdateData
	}
	return nil
}

// UpdateResponse 更新响应
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListAgentsRequest 列举Agent请求
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{10}
}

// ListAgentsResponse 列举Agent响应
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// AgentInfo Agent信息
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // Agent唯一标识符
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                         // Agent类型(filebeat/telegraf/node_exporter等)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                   // Agent版本号(可选)
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                     // 运行状态(running/stopped/error/starting/stopping)
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                                          // 进程ID(0表示未运行)
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`             // 启动时间(Unix时间戳)
	RestartCount  int32                  `protobuf:"varint,7,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`    // 重启次数
	LastHeartbeat int64                  `protobuf:"varint,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // 最后心跳时间(Unix时间戳)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AgentInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AgentInfo) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *AgentInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

// AgentOperationRequest Agent操作请求
type AgentOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // start, stop, restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOperationRequest) Reset() {
	*x = AgentOperationRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperationRequest) ProtoMessage() {}

func (x *AgentOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperationRequest.ProtoReflect.Descriptor instead.
func (*AgentOperationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *AgentOperationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// AgentOperationResponse Agent操作响应
type AgentOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOperationResponse) Reset() {
	*x = AgentOperationResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperationResponse) ProtoMessage() {}

func (x *AgentOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperationResponse.ProtoReflect.Descriptor instead.
func (*AgentOperationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *AgentOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentOperationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// AgentMetricsRequest Agent指标请求
type AgentMetricsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // 查询时间范围（秒），默认3600
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentMetricsRequest) Reset() {
	*x = AgentMetricsRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetricsRequest) ProtoMessage() {}

func (x *AgentMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetricsRequest.ProtoReflect.Descriptor instead.
func (*AgentMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *AgentMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetricsRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// AgentMetricsResponse Agent指标响应
type AgentMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DataPoints    []*ResourceDataPoint   `protobuf:"bytes,2,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetricsResponse) Reset() {
	*x = AgentMetricsResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetricsResponse) ProtoMessage() {}

func (x *AgentMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetricsResponse.ProtoReflect.Descriptor instead.
func (*AgentMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *AgentMetricsResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetricsResponse) GetDataPoints() []*ResourceDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

// ResourceDataPoint 资源数据点
type ResourceDataPoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // 时间戳(Unix时间戳)
	Cpu            float64                `protobuf:"fixed64,2,opt,name=cpu,proto3" json:"cpu,omitempty"`                                              // CPU使用率(百分比)
	MemoryRss      uint64                 `protobuf:"varint,3,opt,name=memory_rss,json=memoryRss,proto3" json:"memory_rss,omitempty"`                  // 内存占用RSS(字节)
	MemoryVms      uint64                 `protobuf:"varint,4,opt,name=memory_vms,json=memoryVms,proto3" json:"memory_vms,omitempty"`                  // 内存占用VMS(字节)
	DiskReadBytes  uint64                 `protobuf:"varint,5,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`    // 磁盘读取字节数
	DiskWriteBytes uint64                 `protobuf:"varint,6,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"` // 磁盘写入字节数
	OpenFiles      int32                  `protobuf:"varint,7,opt,name=open_files,json=openFiles,proto3" json:"open_files,omitempty"`                  // 打开文件数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceDataPoint) Reset() {
	*x = ResourceDataPoint{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDataPoint) ProtoMessage() {}

func (x *ResourceDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDataPoint.ProtoReflect.Descriptor instead.
func (*ResourceDataPoint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *ResourceDataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ResourceDataPoint) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceDataPoint) GetMemoryRss() uint64 {
	if x != nil {
		return x.MemoryRss
	}
	return 0
}

func (x *ResourceDataPoint) GetMemoryVms() uint64 {
	if x != nil {
		return x.MemoryVms
	}
	return 0
}

func (x *ResourceDataPoint) GetDiskReadBytes() uint64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *ResourceDataPoint) GetDiskWriteBytes() uint64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

func (x *ResourceDataPoint) GetOpenFiles() int32 {
	if x != nil {
		return x.OpenFiles
	}
	return 0
}

// SyncAgentStatesRequest 同步Agent状态请求
type SyncAgentStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	States        []*AgentState          `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAgentStatesRequest) Reset() {
	*x = SyncAgentStatesRequest{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAgentStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAgentStatesRequest) ProtoMessage() {}

func (x *SyncAgentStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAgentStatesRequest.ProtoReflect.Descriptor instead.
func (*SyncAgentStatesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *SyncAgentStatesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncAgentStatesRequest) GetStates() []*AgentState {
	if x != nil {
		return x.States
	}
	return nil
}

// SyncAgentStatesResponse 同步Agent状态响应
type SyncAgentStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAgentStatesResponse) Reset() {
	*x = SyncAgentStatesResponse{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAgentStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAgentStatesResponse) ProtoMessage() {}

func (x *SyncAgentStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAgentStatesResponse.ProtoReflect.Descriptor instead.
func (*SyncAgentStatesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *SyncAgentStatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAgentStatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AgentState Agent状态
type AgentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // running, stopped, error
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`       // Agent类型(filebeat/telegraf/node_exporter等)
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"` // Agent版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_daemon_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_daemon_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *AgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AgentState) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *AgentState) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_proto_daemon_daemon_proto protoreflect.FileDescriptor

const file_pkg_proto_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/daemon/daemon.proto\x12\x05proto\"\xa4\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12:\n" +
	"\x06labels\x18\x05 \x03(\v2\".proto.RegisterRequest.LabelsEntryR\x06labels\x12%\n" +
	"\x0edaemon_version\x18\x06 \x01(\tR\rdaemonVersion\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"a\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x0eMetricsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"E\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\rConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vconfig_type\x18\x02 \x01(\tR\n" +
	"configType\"e\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vconfig_data\x18\x03 \x01(\fR\n" +
	"configData\"\xd6\x01\n" +
	"\rUpdateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1f\n" +
	"\vupdate_data\x18\a \x01(\fR\n" +
	"updateData\"D\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListAgentsRequest\">\n" +
	"\x12ListAgentsResponse\x12(\n" +
	"\x06agents\x18\x01 \x03(\v2\x10.proto.AgentInfoR\x06agents\"\xde\x01\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12#\n" +
	"\rrestart_count\x18\a \x01(\x05R\frestartCount\x12%\n" +
	"\x0elast_heartbeat\x18\b \x01(\x03R\rlastHeartbeat\"P\n" +
	"\x15AgentOperationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"W\n" +
	"\x16AgentOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"[\n" +
	"\x13AgentMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x03R\x0fdurationSeconds\"l\n" +
	"\x14AgentMetricsResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\vdata_points\x18\x02 \x03(\v2\x18.proto.ResourceDataPointR\n" +
	"dataPoints\"\xf2\x01\n" +
	"\x11ResourceDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x01R\x03cpu\x12\x1d\n" +
	"\n" +
	"memory_rss\x18\x03 \x01(\x04R\tmemoryRss\x12\x1d\n" +
	"\n" +
	"memory_vms\x18\x04 \x01(\x04R\tmemoryVms\x12&\n" +
	"\x0fdisk_read_bytes\x18\x05 \x01(\x04R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\x06 \x01(\x04R\x0ediskWriteBytes\x12\x1d\n" +
	"\n" +
	"open_files\x18\a \x01(\x05R\topenFiles\"\\\n" +
	"\x16SyncAgentStatesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x06states\x18\x02 \x03(\v2\x11.proto.AgentStateR\x06states\"M\n" +
	"\x17SyncAgentStatesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\n" +
	"AgentState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion2\xef\x04\n" +
	"\rDaemonService\x12;\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponse\x12>\n" +
	"\rReportMetrics\x12\x15.proto.MetricsRequest\x1a\x16.proto.MetricsResponse\x128\n" +
	"\tGetConfig\x12\x14.proto.ConfigRequest\x1a\x15.proto.ConfigResponse\x129\n" +
	"\n" +
	"PushUpdate\x12\x14.proto.UpdateRequest\x1a\x15.proto.UpdateResponse\x12A\n" +
	"\n" +
	"ListAgents\x12\x18.proto.ListAgentsRequest\x1a\x19.proto.ListAgentsResponse\x12K\n" +
	"\fOperateAgent\x12\x1c.proto.AgentOperationRequest\x1a\x1d.proto.AgentOperationResponse\x12J\n" +
	"\x0fGetAgentMetrics\x12\x1a.proto.AgentMetricsRequest\x1a\x1b.proto.AgentMetricsResponse\x12P\n" +
	"\x0fSyncAgentStates\x12\x1d.proto.SyncAgentStatesRequest\x1a\x1e.proto.SyncAgentStatesResponseBGZEgithub.com/bingooyong/ops-scaffold-framework/manager/pkg/proto/daemonb\x06proto3"

var (
	file_pkg_proto_daemon_daemon_proto_rawDescOnce sync.Once
	file_pkg_proto_daemon_daemon_proto_rawDescData []byte
)

func file_pkg_proto_daemon_daemon_proto_rawDescGZIP() []byte {
	file_pkg_proto_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_proto_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_daemon_daemon_proto_rawDesc), len(file_pkg_proto_daemon_daemon_proto_rawDesc)))
	})
	return file_pkg_proto_daemon_daemon_proto_rawDescData
}

var file_pkg_proto_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_proto_daemon_daemon_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: proto.RegisterRequest
	(*RegisterResponse)(nil),        // 1: proto.RegisterResponse
	(*HeartbeatRequest)(nil),        // 2: proto.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: proto.HeartbeatResponse
	(*MetricsRequest)(nil),          // 4: proto.MetricsRequest
	(*MetricsResponse)(nil),         // 5: proto.MetricsResponse
	(*ConfigRequest)(nil),           // 6: proto.ConfigRequest
	(*ConfigResponse)(nil),          // 7: proto.ConfigResponse
	(*UpdateRequest)(nil),           // 8: proto.UpdateRequest
	(*UpdateResponse)(nil),          // 9: proto.UpdateResponse
	(*ListAgentsRequest)(nil),       // 10: proto.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 11: proto.ListAgentsResponse
	(*AgentInfo)(nil),               // 12: proto.AgentInfo
	(*AgentOperationRequest)(nil),   // 13: proto.AgentOperationRequest
	(*AgentOperationResponse)(nil),  // 14: proto.AgentOperationResponse
	(*AgentMetricsRequest)(nil),     // 15: proto.AgentMetricsRequest
	(*AgentMetricsResponse)(nil),    // 16: proto.AgentMetricsResponse
	(*ResourceDataPoint)(nil),       // 17: proto.ResourceDataPoint
	(*SyncAgentStatesRequest)(nil),  // 18: proto.SyncAgentStatesRequest
	(*SyncAgentStatesResponse)(nil), // 19: proto.SyncAgentStatesResponse
	(*AgentState)(nil),              // 20: proto.AgentState
	nil,                             // 21: proto.RegisterRequest.LabelsEntry
}
var file_pkg_proto_daemon_daemon_proto_depIdxs = []int32{
	21, // 0: proto.RegisterRequest.labels:type_name -> proto.RegisterRequest.LabelsEntry
	12, // 1: proto.ListAgentsResponse.agents:type_name -> proto.AgentInfo
	17, // 2: proto.AgentMetricsResponse.data_points:type_name -> proto.ResourceDataPoint
	20, // 3: proto.SyncAgentStatesRequest.states:type_name -> proto.AgentState
	0,  // 4: proto.DaemonService.Register:input_type -> proto.RegisterRequest
	2,  // 5: proto.DaemonService.Heartbeat:input_type -> proto.HeartbeatRequest
	4,  // 6: proto.DaemonService.ReportMetrics:input_type -> proto.MetricsRequest
	6,  // 7: proto.DaemonService.GetConfig:input_type -> proto.ConfigRequest
	8,  // 8: proto.DaemonService.PushUpdate:input_type -> proto.UpdateRequest
	10, // 9: proto.DaemonService.ListAgents:input_type -> proto.ListAgentsRequest
	13, // 10: proto.DaemonService.OperateAgent:input_type -> proto.AgentOperationRequest
	15, // 11: proto.DaemonService.GetAgentMetrics:input_type -> proto.AgentMetricsRequest
	18, // 12: proto.DaemonService.SyncAgentStates:input_type -> proto.SyncAgentStatesRequest
	1,  // 13: proto.DaemonService.Register:output_type -> proto.RegisterResponse
	3,  // 14: proto.DaemonService.Heartbeat:output_type -> proto.HeartbeatResponse
	5,  // 15: proto.DaemonService.ReportMetrics:output_type -> proto.MetricsResponse
	7,  // 16: proto.DaemonService.GetConfig:output_type -> proto.ConfigResponse
	9,  // 17: proto.DaemonService.PushUpdate:output_type -> proto.UpdateResponse
	11, // 18: proto.DaemonService.ListAgents:output_type -> proto.ListAgentsResponse
	14, // 19: proto.DaemonService.OperateAgent:output_type -> proto.AgentOperationResponse
	16, // 20: proto.DaemonService.GetAgentMetrics:output_type -> proto.AgentMetricsResponse
	19, // 21: proto.DaemonService.SyncAgentStates:output_type -> proto.SyncAgentStatesResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_daemon_daemon_proto_init() }
func file_pkg_proto_daemon_daemon_proto_init() {
	if File_pkg_proto_daemon_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_daemon_daemon_proto_rawDesc), len(file_pkg_proto_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_proto_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_pkg_proto_daemon_daemon_proto_msgTypes,
	}.Build()
	File_pkg_proto_daemon_daemon_proto = out.File
	file_pkg_proto_daemon_daemon_proto_goTypes = nil
	file_pkg_proto_daemon_daemon_proto_depIdxs = nil
}
